const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const seedProducts=[
{id:1,name:'Chicken',cost:190,price:260,stock:38,reorder:10},
{id:2,name:'Mutton',cost:690,price:820,stock:14,reorder:5}
];
const store={
 products:JSON.parse(localStorage.getItem('tk_products')||'null')||seedProducts,
 invoices:JSON.parse(localStorage.getItem('tk_invoices')||'[]'),
 expenses:JSON.parse(localStorage.getItem('tk_expenses')||'[]')
};
const save=()=>{localStorage.setItem('tk_products',JSON.stringify(store.products));localStorage.setItem('tk_invoices',JSON.stringify(store.invoices));localStorage.setItem('tk_expenses',JSON.stringify(store.expenses));};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const today=()=>new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function showApp(mode='Demo data'){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#modeBadge').textContent=mode;renderAll(); }

$('#demoLogin').onclick=()=>showApp('Demo data');
$('#logout').onclick=async()=>{if(window.tkCloud?.enabled){try{await window.tkCloud.auth.signOut()}catch{}} $('#app').classList.add('hidden');$('#login').classList.remove('hidden');};

if(window.tkCloud?.enabled){$('#cloudStatus').textContent='Supabase is configured. Sign in with your production account.'} else {$('#cloudStatus').textContent=window.tkCloud?.reason||'Cloud login is not configured.'}
$('#cloudLogin').onsubmit=async e=>{e.preventDefault();if(!window.tkCloud?.enabled)return toast('Add the Supabase publishable key first');try{const {data,error}=await window.tkCloud.auth.signIn($('#loginEmail').value,$('#loginPassword').value);if(error)throw error;showApp(data?.user?'Cloud connected':'Cloud session')}catch(err){toast(err.message||'Sign in failed')}};

const titles={dashboard:['OVERVIEW','Business Dashboard'],billing:['BILLING','Create Invoice'],inventory:['INVENTORY','Stock Management'],customers:['CRM','Customers'],expenses:['COSTS','Expenses'],history:['RECORDS','Invoice History'],reports:['ANALYTICS','Business Reports']};
function gotoView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#eyebrow').textContent=titles[id][0];$('#title').textContent=titles[id][1];if(innerWidth<680)scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(b=>b.onclick=()=>gotoView(b.dataset.view));$$('.goto-billing').forEach(b=>b.onclick=()=>gotoView('billing'));$$('[data-go]').forEach(b=>b.onclick=()=>gotoView(b.dataset.go));

function productOptions(){const s=$('#product');const current=s.value;s.innerHTML=store.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(current&&store.products.some(p=>String(p.id)===current))s.value=current;syncRate()}
function selectedProduct(){return store.products.find(p=>String(p.id)===$('#product').value)||store.products[0]}
function syncRate(){const p=selectedProduct();if(p)$('#rate').value=p.price;updatePreview()}
$('#product').onchange=syncRate;['#qty','#rate','#discount','#customerName','#phone','#paymentMethod','#paymentStatus'].forEach(id=>$(id).addEventListener('input',updatePreview));
function calcTotal(){return Math.max(0,(Number($('#qty').value)||0)*(Number($('#rate').value)||0)-(Number($('#discount').value)||0))}
function updatePreview(){const p=selectedProduct()||{name:'Product'};const total=calcTotal();$('#previewTotal').textContent=money(total);$('#preview').innerHTML=`<div class="bill-head"><div><b>THATHA KADAI</b><div class="muted">Fresh meat • Sunday shop</div></div><div class="text-right"><b>INVOICE</b><div class="muted">Preview</div></div></div><p><b>Customer:</b> ${esc($('#customerName').value||'Customer name')}</p><p><b>Phone:</b> ${esc($('#phone').value||'—')}</p><div class="line-item"><span>${esc(p.name)} × ${$('#qty').value||0}</span><b>${money((Number($('#qty').value)||0)*(Number($('#rate').value)||0))}</b></div><div class="line-item"><span>Discount</span><span>− ${money($('#discount').value)}</span></div><div class="line-item"><span>Payment</span><span>${esc($('#paymentMethod').value.toUpperCase())} · ${esc($('#paymentStatus').value)}</span></div><div class="bill-total"><span>Total</span><span>${money(total)}</span></div>`}

$('#invoiceForm').onsubmit=e=>{e.preventDefault();const p=selectedProduct();const qty=Number($('#qty').value);if(!p||qty<=0)return;if(qty>p.stock)return toast('Not enough stock');const subtotal=qty*Number($('#rate').value);const inv={id:'TK-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6),customer:$('#customerName').value.trim(),phone:$('#phone').value.trim(),product:p.name,productId:p.id,qty,rate:Number($('#rate').value),cost:Number(p.cost||0),discount:Number($('#discount').value)||0,subtotal,total:calcTotal(),paymentMethod:$('#paymentMethod').value,paymentStatus:$('#paymentStatus').value,date:today(),ts:Date.now()};store.invoices.unshift(inv);p.stock=Math.max(0,p.stock-qty);save();e.target.reset();$('#qty').value=1;$('#discount').value=0;productOptions();renderAll();toast('Invoice created');gotoView('history')};

function renderInventory(){const body=$('#inventoryRows');body.innerHTML=store.products.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${money(p.cost||0)}</td><td>${money(p.price)}</td><td>${p.stock} kg</td><td>${p.reorder} kg</td><td><span class="status ${p.stock<=p.reorder?'low':''}">${p.stock<=p.reorder?'Low stock':'Healthy'}</span></td><td><button class="action-btn" onclick="editProduct('${p.id}')">Edit</button><button class="action-btn danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No products yet.</td></tr>'}
window.deleteProduct=id=>{if(store.products.length===1)return toast('Keep at least one product');if(!confirm('Delete this product?'))return;store.products=store.products.filter(p=>String(p.id)!==String(id));save();renderAll();toast('Product deleted')};
window.editProduct=id=>{const p=store.products.find(x=>String(x.id)===String(id));if(!p)return;$('#productDialogTitle').textContent='Edit product';$('#pId').value=p.id;$('#pName').value=p.name;$('#pCost').value=p.cost||0;$('#pPrice').value=p.price;$('#pStock').value=p.stock;$('#pReorder').value=p.reorder;$('#productDialog').showModal()};
$('#addProduct').onclick=()=>{$('#productForm').reset();$('#pId').value='';$('#pReorder').value=5;$('#productDialogTitle').textContent='Add product';$('#productDialog').showModal()};
$('#cancelProduct').onclick=()=>$('#productDialog').close();
$('#productForm').onsubmit=e=>{e.preventDefault();const id=$('#pId').value;const data={name:$('#pName').value.trim(),cost:Number($('#pCost').value),price:Number($('#pPrice').value),stock:Number($('#pStock').value),reorder:Number($('#pReorder').value)};if(id){Object.assign(store.products.find(p=>String(p.id)===id),data)}else store.products.push({id:Date.now(),...data});save();$('#productDialog').close();renderAll();toast(id?'Product updated':'Product added')};

function customers(){const map={};store.invoices.forEach(i=>{const key=(i.phone||i.customer).toLowerCase();if(!map[key])map[key]={name:i.customer,phone:i.phone,orders:0,total:0,last:i.date,ts:i.ts};map[key].orders++;map[key].total+=i.total;if(i.ts>map[key].ts){map[key].last=i.date;map[key].ts=i.ts}});return Object.values(map)}
function renderCustomers(){const q=($('#customerSearch').value||'').toLowerCase();const list=customers().filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q));$('#customerRows').innerHTML=list.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone||'—')}</td><td>${c.orders}</td><td>${money(c.total)}</td><td>${c.last}</td></tr>`).join('')||'<tr><td colspan="5">No matching customers.</td></tr>'}
$('#customerSearch').oninput=renderCustomers;

$('#expenseForm').onsubmit=e=>{e.preventDefault();store.expenses.unshift({id:Date.now(),category:$('#expenseCategory').value.trim(),amount:Number($('#expenseAmount').value),note:$('#expenseNote').value.trim(),date:today(),ts:Date.now()});save();e.target.reset();renderAll();toast('Expense saved')};
function renderExpenses(){const total=store.expenses.reduce((a,b)=>a+b.amount,0);$('#expenseTotal').textContent=money(total);$('#expenseList').innerHTML=store.expenses.map(x=>`<div class="expense-item"><div><b>${esc(x.category)}</b><small>${esc(x.note||x.date)}</small></div><div><b>${money(x.amount)}</b> <button class="action-btn danger" onclick="deleteExpense('${x.id}')">×</button></div></div>`).join('')||'<p class="muted">No expenses recorded.</p>'}
window.deleteExpense=id=>{if(!confirm('Delete this expense?'))return;store.expenses=store.expenses.filter(x=>String(x.id)!==String(id));save();renderAll();toast('Expense deleted')};

function invoiceRow(i,compact=false){const payment=`<span class="status ${i.paymentStatus==='unpaid'?'low':''}">${esc(i.paymentStatus||'paid')}</span>`;return compact?`<tr><td>${esc(i.id)}</td><td>${esc(i.customer)}</td><td>${esc(i.product)}</td><td>${money(i.total)}</td><td>${payment}</td><td>${i.date}</td></tr>`:`<tr><td><b>${esc(i.id)}</b></td><td>${esc(i.customer)}</td><td>${esc(i.product)} × ${i.qty}</td><td><b>${money(i.total)}</b></td><td>${payment}</td><td>${i.date}</td><td><button class="action-btn" onclick="printInvoice('${i.id}')">Print</button><button class="action-btn" onclick="shareInvoice('${i.id}')">WhatsApp</button><button class="action-btn danger" onclick="deleteInvoice('${i.id}')">Delete</button></td></tr>`}
function renderInvoices(){const q=($('#invoiceSearch').value||'').toLowerCase();const filtered=store.invoices.filter(i=>(i.id+' '+i.customer+' '+i.phone).toLowerCase().includes(q));$('#historyRows').innerHTML=filtered.map(i=>invoiceRow(i)).join('')||'<tr><td colspan="7">No matching invoices.</td></tr>';$('#recent').innerHTML=store.invoices.slice(0,5).map(i=>invoiceRow(i,true)).join('')||'<tr><td colspan="6">Create your first invoice.</td></tr>'}
$('#invoiceSearch').oninput=renderInvoices;
window.deleteInvoice=id=>{if(!confirm('Delete invoice and restore stock?'))return;const i=store.invoices.find(x=>x.id===id);if(i){const p=store.products.find(x=>String(x.id)===String(i.productId));if(p)p.stock+=i.qty}store.invoices=store.invoices.filter(x=>x.id!==id);save();renderAll();toast('Invoice deleted')};
window.shareInvoice=id=>{const i=store.invoices.find(x=>x.id===id);if(!i)return;const text=`THATHA KADAI\nInvoice: ${i.id}\nCustomer: ${i.customer}\n${i.product} × ${i.qty} kg @ ₹${i.rate}\nDiscount: ₹${i.discount}\nTotal: ₹${i.total}\nPayment: ${(i.paymentMethod||'cash').toUpperCase()} (${i.paymentStatus||'paid'})\nDate: ${i.date}\nThank you for your purchase!`;const phone=(i.phone||'').replace(/\D/g,'');window.open(`https://wa.me/${phone.length===10?'91'+phone:phone}?text=${encodeURIComponent(text)}`,'_blank')};
window.printInvoice=id=>{const i=store.invoices.find(x=>x.id===id);if(!i)return;const w=open('','_blank','width=720,height=900');w.document.write(`<!doctype html><html><head><title>${esc(i.id)}</title><style>body{font-family:Arial;padding:40px;color:#111}.top{display:flex;justify-content:space-between;border-bottom:3px solid #111;padding-bottom:16px}.row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #ddd}.total{font-size:24px;font-weight:700}.muted{color:#666}</style></head><body><div class="top"><div><h2>THATHA KADAI</h2><div class="muted">Business OS Invoice</div></div><div><b>${esc(i.id)}</b><div>${i.date}</div></div></div><p><b>Customer:</b> ${esc(i.customer)}</p><p><b>Phone:</b> ${esc(i.phone||'—')}</p><div class="row"><span>${esc(i.product)} × ${i.qty} kg</span><b>${money(i.subtotal||i.qty*i.rate)}</b></div><div class="row"><span>Discount</span><span>− ${money(i.discount)}</span></div><div class="row total"><span>Total</span><span>${money(i.total)}</span></div><p>Payment: ${(i.paymentMethod||'cash').toUpperCase()} · ${i.paymentStatus||'paid'}</p><p class="muted">Thank you!</p><script>print()<\/script></body></html>`);w.document.close()};

function renderDashboard(){const revenue=store.invoices.reduce((a,b)=>a+b.total,0),expenses=store.expenses.reduce((a,b)=>a+b.amount,0),cogs=store.invoices.reduce((a,b)=>a+(Number(b.cost||0)*Number(b.qty||0)),0);$('#revenue').textContent=money(revenue);$('#profit').textContent=money(revenue-cogs-expenses);$('#invoiceCount').textContent=store.invoices.length;$('#lowStock').textContent=store.products.filter(p=>p.stock<=p.reorder).length;$('#alerts').innerHTML=store.products.map(p=>`<div class="alert"><div><b>${esc(p.name)}</b><div class="muted">${p.stock} kg available</div></div><span class="status ${p.stock<=p.reorder?'low':''}">${p.stock<=p.reorder?'Restock':'Good'}</span></div>`).join('');const daily={};store.invoices.slice().reverse().forEach(i=>daily[i.date]=(daily[i.date]||0)+i.total);const vals=Object.entries(daily).slice(-7);const max=Math.max(...vals.map(v=>v[1]),1);$('#bars').innerHTML=vals.length?vals.map(([d,v])=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(8,v/max*180)}px" title="${money(v)}"></div>${esc(d.slice(0,6))}</div>`).join(''):'<p class="muted">Revenue chart appears after invoices are created.</p>'}

function renderReports(){const revenue=store.invoices.reduce((a,b)=>a+b.total,0),expenses=store.expenses.reduce((a,b)=>a+b.amount,0);$('#avgOrder').textContent=money(store.invoices.length?revenue/store.invoices.length:0);$('#inventoryValue').textContent=money(store.products.reduce((a,p)=>a+(Number(p.cost||0)*Number(p.stock||0)),0));$('#customerCount').textContent=customers().length;$('#reportExpenses').textContent=money(expenses);const prod={};store.invoices.forEach(i=>{prod[i.product]=prod[i.product]||{qty:0,revenue:0};prod[i.product].qty+=Number(i.qty);prod[i.product].revenue+=Number(i.total)});$('#productPerformance').innerHTML=Object.entries(prod).map(([name,v])=>`<div class="report-row"><div><b>${esc(name)}</b><small>${v.qty.toFixed(1)} kg sold</small></div><strong>${money(v.revenue)}</strong></div>`).join('')||'<p class="muted">No sales yet.</p>';const pay={};store.invoices.forEach(i=>pay[i.paymentMethod||'cash']=(pay[i.paymentMethod||'cash']||0)+i.total);$('#paymentMix').innerHTML=Object.entries(pay).map(([name,v])=>`<div class="report-row"><div><b>${esc(name.toUpperCase())}</b></div><strong>${money(v)}</strong></div>`).join('')||'<p class="muted">No payments yet.</p>'}

$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),products:store.products,invoices:store.invoices,expenses:store.expenses},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='thatha-kadai-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')};

function renderAll(){productOptions();renderInventory();renderCustomers();renderExpenses();renderInvoices();renderDashboard();renderReports();updatePreview()}
renderAll();
