const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const seedProducts=[
{id:1,name:'Oversized Linen Shirt',cost:640,price:1299,stock:24,reorder:8},
{id:2,name:'Wide Leg Trousers',cost:720,price:1599,stock:16,reorder:6},
{id:3,name:'Satin Midi Dress',cost:980,price:2199,stock:9,reorder:5},
{id:4,name:'Classic Denim Jacket',cost:1100,price:2499,stock:5,reorder:5},
{id:5,name:'Ribbed Knit Top',cost:410,price:899,stock:31,reorder:10},
{id:6,name:'Minimal Tote Bag',cost:360,price:799,stock:18,reorder:7}
];
const seedInvoices=[
{id:'MF-2026-1842',customer:'Priya Raman',phone:'9876543210',product:'Satin Midi Dress',productId:3,qty:1,rate:2199,cost:980,discount:200,subtotal:2199,total:1999,paymentMethod:'upi',paymentStatus:'paid',date:'05 Sep 2026',ts:1788591000000},
{id:'MF-2026-1798',customer:'Nithya S',phone:'9123456780',product:'Oversized Linen Shirt',productId:1,qty:2,rate:1299,cost:640,discount:98,subtotal:2598,total:2500,paymentMethod:'card',paymentStatus:'paid',date:'05 Sep 2026',ts:1788587400000},
{id:'MF-2026-1712',customer:'Harini M',phone:'9988776655',product:'Wide Leg Trousers',productId:2,qty:1,rate:1599,cost:720,discount:0,subtotal:1599,total:1599,paymentMethod:'upi',paymentStatus:'paid',date:'04 Sep 2026',ts:1788502200000},
{id:'MF-2026-1660',customer:'Aishwarya K',phone:'9000011111',product:'Minimal Tote Bag',productId:6,qty:2,rate:799,cost:360,discount:100,subtotal:1598,total:1498,paymentMethod:'cash',paymentStatus:'paid',date:'03 Sep 2026',ts:1788415800000},
{id:'MF-2026-1594',customer:'Divya R',phone:'9444455555',product:'Ribbed Knit Top',productId:5,qty:3,rate:899,cost:410,discount:197,subtotal:2697,total:2500,paymentMethod:'upi',paymentStatus:'paid',date:'02 Sep 2026',ts:1788329400000}
];
const seedExpenses=[
{id:1,category:'Instagram Ads',amount:3200,note:'September launch campaign',date:'04 Sep 2026',ts:1788500000000},
{id:2,category:'Packaging',amount:1450,note:'Premium carry bags',date:'02 Sep 2026',ts:1788320000000}
];
const store={
 products:JSON.parse(localStorage.getItem('mf_products')||'null')||seedProducts,
 invoices:JSON.parse(localStorage.getItem('mf_invoices')||'null')||seedInvoices,
 expenses:JSON.parse(localStorage.getItem('mf_expenses')||'null')||seedExpenses
};
const save=()=>{localStorage.setItem('mf_products',JSON.stringify(store.products));localStorage.setItem('mf_invoices',JSON.stringify(store.invoices));localStorage.setItem('mf_expenses',JSON.stringify(store.expenses));};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const today=()=>new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function showApp(mode='Demo workspace'){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#modeBadge').textContent=mode;renderAll()}
$('#demoLogin').onclick=()=>showApp('Demo workspace');
$('#logout').onclick=async()=>{if(window.tkCloud?.enabled){try{await window.tkCloud.auth.signOut()}catch{}}$('#app').classList.add('hidden');$('#login').classList.remove('hidden')};
if(window.tkCloud?.enabled)$('#cloudStatus').textContent='Supabase cloud connection ready.';else $('#cloudStatus').textContent=window.tkCloud?.reason||'Cloud login is not configured.';
$('#cloudLogin').onsubmit=async e=>{e.preventDefault();if(!window.tkCloud?.enabled)return toast('Cloud connection is unavailable');try{const {data,error}=await window.tkCloud.auth.signIn($('#loginEmail').value,$('#loginPassword').value);if(error)throw error;showApp(data?.user?'Cloud workspace':'Cloud session')}catch(err){toast(err.message||'Sign in failed')}};

const titles={dashboard:['STORE OVERVIEW','Good evening, Senthil.'],billing:['POINT OF SALE','Create a new sale'],inventory:['CATALOGUE','Product inventory'],customers:['CLIENTELING','Customer relationships'],expenses:['OPERATIONS','Store expenses'],history:['ORDERS','Sales history'],reports:['RETAIL INTELLIGENCE','Performance analytics']};
function gotoView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#eyebrow').textContent=titles[id][0];$('#title').textContent=titles[id][1];if(innerWidth<820)scrollTo({top:0,behavior:'smooth'})}
$$('.nav[data-view]').forEach(b=>b.onclick=()=>gotoView(b.dataset.view));$$('.goto-billing').forEach(b=>b.onclick=()=>gotoView('billing'));$$('[data-go]').forEach(b=>b.onclick=()=>gotoView(b.dataset.go));

function productOptions(){const s=$('#product');const current=s.value;s.innerHTML=store.products.map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.price)}</option>`).join('');if(current&&store.products.some(p=>String(p.id)===current))s.value=current;syncRate()}
function selectedProduct(){return store.products.find(p=>String(p.id)===$('#product').value)||store.products[0]}
function syncRate(){const p=selectedProduct();if(p)$('#rate').value=p.price;updatePreview()}
$('#product').onchange=syncRate;['#qty','#rate','#discount','#customerName','#phone','#paymentMethod','#paymentStatus'].forEach(id=>$(id).addEventListener('input',updatePreview));
function calcTotal(){return Math.max(0,(Number($('#qty').value)||0)*(Number($('#rate').value)||0)-(Number($('#discount').value)||0))}
function updatePreview(){const p=selectedProduct()||{name:'Fashion item'};const qty=Number($('#qty').value)||0,total=calcTotal();$('#previewTotal').textContent=money(total);$('#preview').innerHTML=`<div class="bill-head"><div><b style="font-family:Playfair Display,serif;font-size:22px">ATELIER VOGUE</b><div class="muted">Curated fashion · Tiruppur</div></div><div class="text-right"><b>RECEIPT</b><div class="muted">ModeFlow POS</div></div></div><p><b>Customer</b><br>${esc($('#customerName').value||'Walk-in customer')}</p><p class="muted">${esc($('#phone').value||'No mobile number')}</p><div class="line-item"><span>${esc(p.name)} × ${qty}</span><b>${money(qty*(Number($('#rate').value)||0))}</b></div><div class="line-item"><span>Discount</span><span>− ${money($('#discount').value)}</span></div><div class="line-item"><span>Payment</span><span>${esc($('#paymentMethod').value.toUpperCase())} · ${esc($('#paymentStatus').value)}</span></div><div class="bill-total"><span>Total</span><span>${money(total)}</span></div><p class="muted" style="margin-top:28px;font-size:11px">Thank you for shopping with Atelier Vogue.</p>`}
$('#invoiceForm').onsubmit=e=>{e.preventDefault();const p=selectedProduct(),qty=Number($('#qty').value);if(!p||qty<=0)return;if(qty>p.stock)return toast('Not enough stock for this sale');const subtotal=qty*Number($('#rate').value),inv={id:'MF-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-4),customer:$('#customerName').value.trim(),phone:$('#phone').value.trim(),product:p.name,productId:p.id,qty,rate:Number($('#rate').value),cost:Number(p.cost||0),discount:Number($('#discount').value)||0,subtotal,total:calcTotal(),paymentMethod:$('#paymentMethod').value,paymentStatus:$('#paymentStatus').value,date:today(),ts:Date.now()};store.invoices.unshift(inv);p.stock=Math.max(0,p.stock-qty);save();e.target.reset();$('#qty').value=1;$('#discount').value=0;productOptions();renderAll();toast('Sale completed successfully');gotoView('history')};

function renderInventory(){const q=($('#productSearch')?.value||'').toLowerCase();const list=store.products.filter(p=>p.name.toLowerCase().includes(q));$('#inventoryRows').innerHTML=list.map(p=>`<tr><td><div><b>${esc(p.name)}</b><div class="muted" style="font-size:10px;margin-top:3px">SKU MF-${String(p.id).padStart(4,'0')}</div></div></td><td>${money(p.cost||0)}</td><td><b>${money(p.price)}</b></td><td>${p.stock} pcs</td><td>${p.reorder} pcs</td><td><span class="status ${p.stock<=p.reorder?'low':''}">${p.stock<=p.reorder?'Low stock':'In stock'}</span></td><td><button class="action-btn" onclick="editProduct('${p.id}')">Edit</button><button class="action-btn danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No matching products.</td></tr>'}
if($('#productSearch'))$('#productSearch').oninput=renderInventory;
window.deleteProduct=id=>{if(store.products.length===1)return toast('Keep at least one product');if(!confirm('Delete this product?'))return;store.products=store.products.filter(p=>String(p.id)!==String(id));save();renderAll();toast('Product deleted')};
window.editProduct=id=>{const p=store.products.find(x=>String(x.id)===String(id));if(!p)return;$('#productDialogTitle').textContent='Edit product';$('#pId').value=p.id;$('#pName').value=p.name;$('#pCost').value=p.cost||0;$('#pPrice').value=p.price;$('#pStock').value=p.stock;$('#pReorder').value=p.reorder;$('#productDialog').showModal()};
$('#addProduct').onclick=()=>{$('#productForm').reset();$('#pId').value='';$('#pReorder').value=5;$('#productDialogTitle').textContent='Add product';$('#productDialog').showModal()};$('#cancelProduct').onclick=()=>$('#productDialog').close();
$('#productForm').onsubmit=e=>{e.preventDefault();const id=$('#pId').value,data={name:$('#pName').value.trim(),cost:Number($('#pCost').value),price:Number($('#pPrice').value),stock:Number($('#pStock').value),reorder:Number($('#pReorder').value)};if(id)Object.assign(store.products.find(p=>String(p.id)===id),data);else store.products.push({id:Date.now(),...data});save();$('#productDialog').close();renderAll();toast(id?'Product updated':'Product added')};

function customers(){const map={};store.invoices.forEach(i=>{const key=(i.phone||i.customer).toLowerCase();if(!map[key])map[key]={name:i.customer,phone:i.phone,orders:0,total:0,last:i.date,ts:i.ts};map[key].orders++;map[key].total+=i.total;if(i.ts>map[key].ts){map[key].last=i.date;map[key].ts=i.ts}});return Object.values(map)}
function initials(name){return name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function renderCustomers(){const q=($('#customerSearch').value||'').toLowerCase();const list=customers().filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q));$('#customerRows').innerHTML=list.map(c=>`<tr><td><div style="display:flex;align-items:center;gap:10px"><span class="store-avatar">${esc(initials(c.name))}</span><b>${esc(c.name)}</b></div></td><td>${esc(c.phone||'—')}</td><td>${c.orders}</td><td><b>${money(c.total)}</b></td><td>${c.last}</td></tr>`).join('')||'<tr><td colspan="5">No matching customers.</td></tr>'}
$('#customerSearch').oninput=renderCustomers;

$('#expenseForm').onsubmit=e=>{e.preventDefault();store.expenses.unshift({id:Date.now(),category:$('#expenseCategory').value.trim(),amount:Number($('#expenseAmount').value),note:$('#expenseNote').value.trim(),date:today(),ts:Date.now()});save();e.target.reset();renderAll();toast('Expense added')};
function renderExpenses(){const total=store.expenses.reduce((a,b)=>a+b.amount,0);$('#expenseTotal').textContent=money(total);$('#expenseList').innerHTML=store.expenses.map(x=>`<div class="expense-item"><div><b>${esc(x.category)}</b><small>${esc(x.note||x.date)}</small></div><div><b>${money(x.amount)}</b> <button class="action-btn danger" onclick="deleteExpense('${x.id}')">×</button></div></div>`).join('')||'<p class="muted">No expenses recorded.</p>'}
window.deleteExpense=id=>{if(!confirm('Delete this expense?'))return;store.expenses=store.expenses.filter(x=>String(x.id)!==String(id));save();renderAll();toast('Expense deleted')};

function invoiceRow(i,compact=false){const payment=`<span class="status ${i.paymentStatus==='unpaid'?'low':''}">${esc(i.paymentStatus||'paid')}</span>`;return compact?`<tr><td><b>${esc(i.id)}</b></td><td>${esc(i.customer)}</td><td>${esc(i.product)}</td><td><b>${money(i.total)}</b></td><td>${payment}</td><td>${i.date}</td></tr>`:`<tr><td><b>${esc(i.id)}</b></td><td>${esc(i.customer)}</td><td>${esc(i.product)} × ${i.qty}</td><td><b>${money(i.total)}</b></td><td>${payment}</td><td>${i.date}</td><td><button class="action-btn" onclick="printInvoice('${i.id}')">Print</button><button class="action-btn" onclick="shareInvoice('${i.id}')">WhatsApp</button><button class="action-btn danger" onclick="deleteInvoice('${i.id}')">Delete</button></td></tr>`}
function renderInvoices(){const q=($('#invoiceSearch').value||'').toLowerCase();const filtered=store.invoices.filter(i=>(i.id+' '+i.customer+' '+i.phone).toLowerCase().includes(q));$('#historyRows').innerHTML=filtered.map(i=>invoiceRow(i)).join('')||'<tr><td colspan="7">No matching orders.</td></tr>';$('#recent').innerHTML=store.invoices.slice(0,5).map(i=>invoiceRow(i,true)).join('')||'<tr><td colspan="6">No orders yet.</td></tr>'}
$('#invoiceSearch').oninput=renderInvoices;
window.deleteInvoice=id=>{if(!confirm('Delete order and restore stock?'))return;const i=store.invoices.find(x=>x.id===id);if(i){const p=store.products.find(x=>String(x.id)===String(i.productId));if(p)p.stock+=i.qty}store.invoices=store.invoices.filter(x=>x.id!==id);save();renderAll();toast('Order deleted')};
window.shareInvoice=id=>{const i=store.invoices.find(x=>x.id===id);if(!i)return;const text=`ATELIER VOGUE\nOrder: ${i.id}\nCustomer: ${i.customer}\n${i.product} × ${i.qty}\nTotal: ₹${i.total}\nPayment: ${(i.paymentMethod||'upi').toUpperCase()} (${i.paymentStatus||'paid'})\nDate: ${i.date}\nThank you for shopping with us!`;const phone=(i.phone||'').replace(/\D/g,'');window.open(`https://wa.me/${phone.length===10?'91'+phone:phone}?text=${encodeURIComponent(text)}`,'_blank')};
window.printInvoice=id=>{const i=store.invoices.find(x=>x.id===id);if(!i)return;const w=open('','_blank','width=720,height=900');w.document.write(`<!doctype html><html><head><title>${esc(i.id)}</title><style>body{font-family:Arial;padding:42px;color:#171713}.top{display:flex;justify-content:space-between;border-bottom:2px solid #171713;padding-bottom:18px}.row{display:flex;justify-content:space-between;padding:13px 0;border-bottom:1px solid #ddd}.total{font-size:24px;font-weight:700}.muted{color:#777}</style></head><body><div class="top"><div><h2>ATELIER VOGUE</h2><div class="muted">Powered by ModeFlow</div></div><div><b>${esc(i.id)}</b><div>${i.date}</div></div></div><p><b>Customer:</b> ${esc(i.customer)}</p><p><b>Phone:</b> ${esc(i.phone||'—')}</p><div class="row"><span>${esc(i.product)} × ${i.qty}</span><b>${money(i.subtotal||i.qty*i.rate)}</b></div><div class="row"><span>Discount</span><span>− ${money(i.discount)}</span></div><div class="row total"><span>Total</span><span>${money(i.total)}</span></div><p>Payment: ${(i.paymentMethod||'upi').toUpperCase()} · ${i.paymentStatus||'paid'}</p><p class="muted">Thank you for shopping with Atelier Vogue.</p><script>print()<\/script></body></html>`);w.document.close()};

function renderDashboard(){const revenue=store.invoices.reduce((a,b)=>a+b.total,0),expenses=store.expenses.reduce((a,b)=>a+b.amount,0),cogs=store.invoices.reduce((a,b)=>a+(Number(b.cost||0)*Number(b.qty||0)),0);$('#revenue').textContent=money(revenue);$('#profit').textContent=money(revenue-cogs-expenses);$('#invoiceCount').textContent=store.invoices.length;$('#lowStock').textContent=store.products.filter(p=>p.stock<=p.reorder).length;$('#alerts').innerHTML=store.products.slice().sort((a,b)=>(a.stock/a.reorder)-(b.stock/b.reorder)).slice(0,5).map(p=>`<div class="alert"><div><b>${esc(p.name)}</b><div class="muted">${p.stock} pieces available</div></div><span class="status ${p.stock<=p.reorder?'low':''}">${p.stock<=p.reorder?'Restock':'Healthy'}</span></div>`).join('');const daily={};store.invoices.slice().reverse().forEach(i=>daily[i.date]=(daily[i.date]||0)+i.total);const vals=Object.entries(daily).slice(-7);const max=Math.max(...vals.map(v=>v[1]),1);$('#bars').innerHTML=vals.length?vals.map(([d,v])=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(12,v/max*175)}px" title="${money(v)}"></div>${esc(d.slice(0,6))}</div>`).join(''):'<p class="muted">Sales chart appears after orders are created.</p>'}
function renderReports(){const revenue=store.invoices.reduce((a,b)=>a+b.total,0),expenses=store.expenses.reduce((a,b)=>a+b.amount,0);$('#avgOrder').textContent=money(store.invoices.length?revenue/store.invoices.length:0);$('#inventoryValue').textContent=money(store.products.reduce((a,p)=>a+(Number(p.cost||0)*Number(p.stock||0)),0));$('#customerCount').textContent=customers().length;$('#reportExpenses').textContent=money(expenses);const prod={};store.invoices.forEach(i=>{prod[i.product]=prod[i.product]||{qty:0,revenue:0};prod[i.product].qty+=Number(i.qty);prod[i.product].revenue+=Number(i.total)});$('#productPerformance').innerHTML=Object.entries(prod).sort((a,b)=>b[1].revenue-a[1].revenue).map(([name,v])=>`<div class="report-row"><div><b>${esc(name)}</b><small>${v.qty} units sold</small></div><strong>${money(v.revenue)}</strong></div>`).join('')||'<p class="muted">No sales data yet.</p>';const pay={};store.invoices.forEach(i=>pay[i.paymentMethod||'upi']=(pay[i.paymentMethod||'upi']||0)+i.total);$('#paymentMix').innerHTML=Object.entries(pay).sort((a,b)=>b[1]-a[1]).map(([name,v])=>`<div class="report-row"><div><b>${esc(name.toUpperCase())}</b><small>${revenue?Math.round(v/revenue*100):0}% of sales</small></div><strong>${money(v)}</strong></div>`).join('')||'<p class="muted">No payment data yet.</p>'}
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),products:store.products,invoices:store.invoices,expenses:store.expenses},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='modeflow-retail-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Retail data exported')};
function renderAll(){productOptions();renderInventory();renderCustomers();renderExpenses();renderInvoices();renderDashboard();renderReports();updatePreview()}
renderAll();
