// SalesDesk cart/POS v1 — multi-item atomic checkout.
(function(){
'use strict';if(window.SalesDeskPosV1)return;window.SalesDeskPosV1=true;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const notify=m=>typeof toast==='function'?toast(m):alert(m);let workspace=null,branches=[];const c=()=>window.tkCloud?.client;const products=()=>{try{return typeof store!=='undefined'?(store.products||[]):[]}catch{return[]}};const money=n=>(window.ModeFlowCurrency||'INR')==='USD'?'$'+Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2}):'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
function go(id){if(typeof window.gotoView==='function')window.gotoView(id);else{$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id))}if(id==='cart-sale'){loadBranches();setTimeout(()=>$('#sdPosCustomer')?.focus(),50)}window.SalesDeskFooters?.refresh?.()}
function productOptions(){return products().map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.price||0)}${p.trackStock===false?' · Service':' · Stock '+Number(p.stock||0)}</option>`).join('')}
function mount(){if($('#cart-sale'))return;const nav=$('.sidebar nav'),quick=nav?.querySelector('.nav[data-view="billing"]');if(quick){const t=quick.querySelector('span');if(t)t.textContent='Quick sale'}if(nav){const b=document.createElement('button');b.className='nav';b.dataset.view='cart-sale';b.innerHTML='<i>02</i><span>New sale</span>';b.onclick=()=>go('cart-sale');nav.insertBefore(b,quick||nav.firstChild);$$('.sidebar nav .nav[data-view]').forEach((x,i)=>{const n=x.querySelector('i');if(n)n.textContent=String(i+1).padStart(2,'0')})}
const main=$('#app main');if(!main)return;main.insertAdjacentHTML('beforeend',`<section id="cart-sale" class="view"><div class="page-intro"><div><p class="kicker">SMART CHECKOUT</p><h3>One customer. <em>Any number of items.</em></h3><p>Create a multi-item transaction atomically, update stock once and keep a single invoice trail.</p></div><span class="sd-pro-badge">Atomic checkout</span></div><div class="sd-pro-layout"><article class="sd-pro-card"><div class="sd-pro-form"><label>Customer name<input id="sdPosCustomer" maxlength="160" placeholder="Walk-in customer"></label><label>Mobile<input id="sdPosPhone" maxlength="30" inputmode="tel"></label><label>Branch<select id="sdPosBranch"><option value="">Main / no branch</option></select></label><label>Payment status<select id="sdPosStatus"><option value="paid">Paid</option><option value="partial">Partial</option><option value="unpaid">Unpaid</option></select></label></div><div class="sd-pro-line-head" style="margin-top:18px"><span>PRODUCT / SERVICE</span><span>QTY</span><span>RATE</span><span>TOTAL</span><span></span></div><div id="sdPosLines"></div><div class="sd-pro-actions" style="margin-top:12px"><button class="btn secondary" id="sdPosAdd" type="button">+ Add item</button></div><div class="sd-pro-form" style="margin-top:18px"><label>Discount<input id="sdPosDiscount" type="number" min="0" step="0.01" value="0"></label><label>Payment method<select id="sdPosMethod"><option value="upi">UPI</option><option value="cash">Cash</option><option value="card">Card</option><option value="bank">Bank</option><option value="other">Other</option></select></label></div><div class="sd-pro-total"><span>Total payable</span><strong id="sdPosTotal">₹0</strong></div><button class="btn primary full" id="sdPosComplete" type="button" style="width:100%;min-height:50px">Complete sale</button></article><aside class="sd-pro-card"><p class="kicker">CHECKOUT SAFETY</p><h3>Built for real transactions</h3><div class="sd-pro-stack"><div class="sd-pro-row"><div><b>One database transaction</b><small>Invoice, lines and stock deductions complete together.</small></div><span class="sd-pro-badge">Atomic</span></div><div class="sd-pro-row"><div><b>Duplicate protection</b><small>A unique idempotency key protects accidental double taps.</small></div><span class="sd-pro-badge">Safe</span></div><div class="sd-pro-row"><div><b>Products + services</b><small>Services do not require stock while products remain stock checked.</small></div><span class="sd-pro-badge">Adaptive</span></div><div class="sd-pro-row"><div><b>Payment tracking</b><small>Paid, partial and unpaid transactions feed receivables.</small></div><span class="sd-pro-badge">Live</span></div></div></aside></div></section>`);$('#sdPosAdd').onclick=addLine;$('#sdPosDiscount').oninput=recalc;$('#sdPosComplete').onclick=complete;addLine();window.SalesDeskFooters?.refresh?.()}
function addLine(){const wrap=$('#sdPosLines');if(!wrap)return;if(!products().length){wrap.innerHTML='<div class="sd-pro-empty">Add a product or service before creating a sale.</div>';return}const row=document.createElement('div');row.className='sd-pro-line';row.innerHTML=`<select class="sd-pro-product">${productOptions()}</select><input class="sd-pos-qty" type="number" min="0.001" step="0.001" value="1"><input class="sd-pos-rate" type="number" min="0" step="0.01" value="0"><div class="sd-pro-line-total">${money(0)}</div><button class="sd-pro-remove" type="button">×</button>`;wrap.appendChild(row);const product=row.querySelector('.sd-pro-product'),rate=row.querySelector('.sd-pos-rate');const sync=()=>{const p=products().find(x=>String(x.id)===product.value);if(p)rate.value=Number(p.price||0);recalc()};product.onchange=sync;row.querySelector('.sd-pos-qty').oninput=recalc;rate.oninput=recalc;row.querySelector('.sd-pro-remove').onclick=()=>{row.remove();if(!wrap.querySelector('.sd-pro-line'))addLine();recalc()};sync()}
function items(){return $$('#sdPosLines .sd-pro-line').map(r=>({product_id:r.querySelector('.sd-pro-product').value,quantity:Number(r.querySelector('.sd-pos-qty').value),rate:Number(r.querySelector('.sd-pos-rate').value)}))}
function recalc(){let subtotal=0;$$('#sdPosLines .sd-pro-line').forEach(r=>{const q=Number(r.querySelector('.sd-pos-qty').value)||0,rate=Number(r.querySelector('.sd-pos-rate').value)||0,v=q*rate;subtotal+=v;r.querySelector('.sd-pro-line-total').textContent=money(v)});const discount=Math.max(0,Number($('#sdPosDiscount')?.value)||0);if($('#sdPosTotal'))$('#sdPosTotal').textContent=money(Math.max(0,subtotal-discount))}
async function loadBranches(){if(!workspace?.id)return;const {data}=await c().from('branches').select('id,name,code').eq('business_id',workspace.id).eq('is_active',true).order('created_at');branches=data||[];const s=$('#sdPosBranch');if(s)s.innerHTML='<option value="">Main / no branch</option>'+branches.map(b=>`<option value="${b.id}">${esc(b.name)} · ${esc(b.code)}</option>`).join('')}
async function complete(){const rows=items(),discount=Number($('#sdPosDiscount').value)||0;if(!rows.length||rows.some(x=>!x.product_id||!Number.isFinite(x.quantity)||x.quantity<=0||!Number.isFinite(x.rate)||x.rate<0))return notify('Check every sale item.');let subtotal=rows.reduce((a,x)=>a+x.quantity*x.rate,0);if(discount<0||discount>subtotal)return notify('Discount cannot exceed subtotal.');for(const x of rows){const p=products().find(y=>String(y.id)===String(x.product_id));if(p?.trackStock!==false&&x.quantity>Number(p.stock||0))return notify(`Not enough stock for ${p.name}`)}const b=$('#sdPosComplete');b.disabled=true;b.textContent='Saving sale…';try{const key=crypto.randomUUID();const {data,error}=await c().rpc('complete_multi_item_sale',{p_business_id:workspace.id,p_customer_name:$('#sdPosCustomer').value.trim()||'Walk-in customer',p_customer_phone:$('#sdPosPhone').value.trim()||null,p_items:rows,p_discount:discount,p_payment_method:$('#sdPosMethod').value,p_payment_status:$('#sdPosStatus').value,p_branch_id:$('#sdPosBranch').value||null,p_idempotency_key:key});if(error)throw error;notify('Sale completed securely');$('#sdPosCustomer').value='';$('#sdPosPhone').value='';$('#sdPosDiscount').value='0';$('#sdPosLines').innerHTML='';addLine();window.dispatchEvent(new CustomEvent('salesdesk:operations-updated',{detail:{invoiceId:data}}));setTimeout(()=>go('history'),350)}catch(x){notify(x.message||'Unable to complete sale')}finally{b.disabled=false;b.textContent='Complete sale'}}
async function activate(detail){workspace=detail;if(!workspace?.id||!c())return;const {error}=await c().from('branches').select('id').eq('business_id',workspace.id).limit(1);if(error)return;mount();loadBranches()}
addEventListener('modeflow:workspace',e=>activate(e.detail));addEventListener('salesdesk:data-refreshed',()=>{if($('#cart-sale')?.classList.contains('active-view')){const selected=$$('.sd-pro-product').map(x=>x.value);$$('#sdPosLines .sd-pro-line').forEach((r,i)=>{const p=r.querySelector('.sd-pro-product');p.innerHTML=productOptions();if(selected[i])p.value=selected[i]})}});if(window.ModeFlowBusiness)activate(window.ModeFlowBusiness);
})();
